[package]
name = "day19"
version = "0.1.0"
authors = ["Thomas Campistron <irevoire@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { git = "https://github.com/irevoire/aoc" }
